version: "3"
services:
  hamachi:
    image: gtfunes/hamachi
    container_name: hamachi
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ${ROOT}:/var/lib/logmein-hamachi:rw
      - /etc/localtime:/etc/localtime